# Generated by Django 6.0 on 2025-12-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bitki Adı ')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='Bitki Türü ')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Ekleme Tarihi ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plant_photos/', verbose_name='Resim Ekle ')),
                ('location', models.CharField(blank=True, choices=[('living_room', 'Salon'), ('kitchen', 'Mutfak'), ('balcony', 'Balkon'), ('bedroom', 'Yatak Odası'), ('bathroom', 'Banyo'), ('office', 'Çalışma Odası'), ('other', 'Diğer')], max_length=100, verbose_name='Evdeki Konumu')),
                ('irrigation_frequency', models.PositiveIntegerField(verbose_name='Sulama Sıklığı (Gün)')),
            ],
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('watered', models.BooleanField(default=False)),
                ('fertilized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.plant')),
            ],
        ),
    ]
